 CREATE TABLE IF NOT EXISTS DEPARTMENT ( 
    NumberOfEmployees INTEGER, 
    SALARY INTEGER,
    DEPARTMENT_NAME STRING,
    DEPARTMENT_CODE INTEGER,
    DEPARTMENT_ID INTEGER
    MANAGER_ID INTEGER
);


INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_CODE, MANAGER_ID, SALARY, NumberOfEmployees) VALUES 
(1, 'HR', 101, 200, 5000, 5),
(2, 'Finance', 102, 201, 7000, 8),
(3, 'IT', 103, 202, 9000, 10),
(4, 'Marketing', 104, 203, 6000, 6),
(5, 'Operations', 105, 204, 7500, 7);

SELECT DEPARTMENT_ID AS "DEPARTMENT CODE"
COUNT(*) AS "NumberOfEmployees"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID
